### ISSUE TITLE
doc

### ISSUE THREAD

**Issue by yz-Python** [InternLM/magic-doc#29]
**Describe the bug**  | **描述 bug **
A clear and concise description of what the bug is. ｜ 简洁地描述下 bug

**To Reproduce** ｜ **复现步骤**
Steps to reproduce the behavior:    ｜ 复现步骤如下 （以某个网站页面为例子）
1. Go to '...'                                          ｜ 1.  某个页面 'https://some.come/some.page'
2. Click on '....'                                     |   2. 点击页面按钮 xxx
3. Scroll down to '....'                         ｜ 3. 滑动页面到 yyy
4. See error                                         |   4. 完成以上操作后，将触发问题

**Expected behavior** ｜ **期望行为**
A clear and concise description of what you expected to happen.  | 简洁描述你所期望的结果

**Screenshots** ｜ **截图** 
If applicable, add screenshots to help explain your problem. ｜ 有图有真相

**Env** | **系统环境**
 - OS: [e.g. iOS]  ｜ 系统
 - Python version ｜ python 版本
 - fariy-doc Version | fairy-doc 版本

**Comment by icecraft** [comment]
closed for no information found
